## First Step :: Function OLS : Compute the OLS estimator and related variables.

### (a) Input y and X

In [86]:
import pandas as pd 
x = pd.read_csv("X.csv").drop(x.columns[len(x.columns)-1], axis =1)
y = pd.read_csv("y.csv",header = None).drop(y.columns[0],axis=1)
X = np.matrix(x).T
Y = np.matrix(y)

In [87]:
Y.shape

(1110, 2)

In [88]:
X.shape

(1110, 3)

### (b) Return some estimates

### Here is the OLS point estimates: y = X$\beta$

In [91]:
beta = np.linalg.inv(X.T * X) * (X.T * Y)
beta

matrix([[ 3.57954473e+03,  1.23479278e+00],
        [ 1.44994394e+03, -1.79300898e-01],
        [ 4.38979146e+03,  1.05381601e+00]])

### The OLS errors can be defined as the Frobenius Norm of the matrix $X*\beta - Y$.

In [109]:
olsErr = np.linalg.norm((X * beta - Y), ord = 'fro')
olsErr

6499724.904096859

### (c) Check whether a constant is included in X

In [167]:
lst=[]
for i in range(X.shape[1]):
    column = X[:,i]
    lst.append(False in [(column[0]-column[j])<0.0001 for j in range(len(column))]) #this attribute of the vector is not a constant
lst

[True, True, True]

#### As you can see, no attribute of the vector x is a constant

### (d) IF no constnat, option to include a constant or not

In [203]:
num= 2 # the value of the constant that will be added into X
newAdded = np.matrix(num * np.ones(X.shape[0])).T
X_new  = np.concatenate((X.T, newAdded.T))
X_new

matrix([[ 2.96,  2.64,  0.36, ..., -7.68,  1.69,  8.41],
        [-2.3 , -1.4 , -1.32, ..., -4.68, -0.74,  3.01],
        [-2.87,  4.19,  0.01, ...,  3.41,  0.19, -0.6 ],
        [ 2.  ,  2.  ,  2.  , ...,  2.  ,  2.  ,  2.  ]])

### (e) Return the projection matrices P amd M, and check whether $PM=0$

In [127]:
P = X * np.linalg.inv(X.T * X) * X.T 
I = np.ones(P.shape[0]**2).reshape(P.shape)
M = I - P
result = P * M 
result.round(0)

matrix([[-0., -0., -0., ..., -0., -0., -0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [-0., -0., -0., ..., -0., -0., -0.],
        ...,
        [-0., -0., -0., ..., -0., -0., -0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

### (f) Check whether the sample equivalent of the condition $E(ex)=0$ is satisfied

In [150]:
e = X * beta - Y
result = 1/ X.shape[1] *e.T * X
result.round(2)

array([[ 0.,  0.,  0.],
       [ 0., -0.,  0.]])

#### As we can see from the result: $E(X*e) = 0$

### (g) $Q_{x,x}=E(x_i,x_i')$

In [134]:
X[0] * X[0].T

matrix([[22.2885]])

In [143]:
Q_xx = 1/X.shape[0] * sum([X[i].T * X[i] for i in range(X.shape[0])])
Q_xx

matrix([[28.83022532,  5.56324117,  4.59701838],
        [ 5.56324117, 10.21579829,  1.45434279],
        [ 4.59701838,  1.45434279, 12.24126225]])

In [145]:
np.linalg.cond(Q_xx)

3.642205298494017

#### So Q_xx is not a sigular matrix

In [146]:
np.linalg.inv(Q_xx)

matrix([[ 0.04065445, -0.02030933, -0.01285427],
        [-0.02030933,  0.10971744, -0.0054083 ],
        [-0.01285427, -0.0054083 ,  0.08716069]])

[True, True, True]

In [162]:
column

matrix([[ 2.96],
        [ 2.64],
        [ 0.36],
        ...,
        [-7.68],
        [ 1.69],
        [ 8.41]])

## Second Step::t_test : Compute t-test whether $\beta_i=b^0$

### (a) Input b0 and other necessary data

### (b) t-test value and flags at 1%, 5% and 10% levels 